# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: yutellite's Blog

title: yutellite

email: yutellite@126.com

# Short description (goes below the title; it will also be used in the RSS feed)
description: This is yutellite's Blog. Life is not easy, so think twice about the happy time of your life and none about the painful time.

# Your name, as you want it to appear underneath each post and in the footer
author: yutellite

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: https://yutellite.github.io/workshop/

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
    - node_modules
    - README.md
    - LICENSE.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - Gruntfile.js
    - package.json
    - script
    - spec
